language: minimal
sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install snapcraft --classic

deploy:
  provider: snap
  snap: tidal
  channel: stable
  skip_cleanup: true
