language: minimal
sudo: true
services:
  - docker

script:
  docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq && cd $(pwd) && snapcraft"

deploy:
  provider: snap
  snap: tidal
  channel: stable
  skip_cleanup: true
